CREATE TABLE T_EMAIL_RECEIVER (
    EMAIL_RECEIVER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL_RECEIVER_SUBJECT VARCHAR(255),
    EMAIL_RECEIVER_MAILBODY TEXT,
    EMAIL_RECEIVER_ORIGIN VARCHAR(500),
    EMAIL_RECEIVER_DESTINY VARCHAR(500),
    EMAIL_RECEIVER_COPY VARCHAR(500),
    EMAIL_RECEIVER_DATEREG DATE
);